# Testa GET /users
GET http://localhost:3000/users
Accept: application/json

###

# Testa GET /users/:id
GET http://localhost:3000/users/39602f41-b43e-4fa8-b7f7-34c7a516740b
Accept: application/json

###

# Testa POST /users
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com"
}

###

# Testa PUT /users/:id
PUT http://localhost:3000/users/39602f41-b43e-4fa8-b7f7-34c7a516740b
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane@example.com"
}

###

# Testa DELETE /users/:id
DELETE http://localhost:3000/users/39602f41-b43e-4fa8-b7f7-34c7a516740b
Accept: application/json
